#name: CI Action
#
#on:
#  push:
#    branches:
#      - main
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - name: Setup Bun
#        run: |
#          curl -fsSL https://bun.sh/install | bash
#          echo "$HOME/.bun/bin" >> $GITHUB_PATH
#      - name: Install dependencies
#        run: bun install
#      - name: ts build
#        run: bun run build
#      - name: Kill existing Bun processes
#        run: pkill -f 'bun' || true
#      - name: Run Script with CI Tag
#        if: contains(github.event.head_commit.message, 'ci:')
#        run: bun start

name: CI Action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH
      - name: Install dependencies
        run: bun install
      - name: ts build
        run: bun run build
      - name: Setup PM2
        run: |
          npm install pm2 -g
      - name: Check if bun-app exists and delete if it does
        run: |
          if pm2 jlist | grep -q '"name":"bun-app"'; then
            pm2 delete bun-app
          fi
      - name: Start Bun with PM2
        if: contains(github.event.head_commit.message, 'ci:')
        run: |
          pm2 start "bun start" --name bun-app
      - name: Save PM2 list
        run: |
          pm2 save
